version: '3'
services:
  runner:
    image: mesg/runner
    ports:
      - 60001:60001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672